import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/shared/Footer";
import CommentSec from "./(blog)/comment-sec/page"; // No dynamic import needed

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Deenix AI Blog",
  description: "Generated by Muhammad Nasrullah",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const blogId = "example-blog-id"; // Hardcoded example, replace with dynamic value if needed

  return (
    <html lang="en">
      <body
        className={raleway.className + "h-full w-full flex flex-1 flex-col"}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          {/* Pass blogId prop to CommentSec */}
          <CommentSec blogId={blogId} />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
